apiVersion: v1
kind: Service
metadata:
  name: spring-boot-example
  labels:
    name: spring-boot-example
spec:
  ports:
    - port: 6060
      targetPort: 6060
  selector:
    app: spring-boot-example
  type: NodePort