 apiVersion: apps/v1
 kind: Deployment
metadata:
  name: spring-boot-kubernetes-skaffold-app
  labels:
    app: spring-boot-kubernetes-skaffold-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-boot-kubernetes-skaffold-app
  template:
    metadata:
      labels:
        app: spring-boot-kubernetes-skaffold-app
    spec:
      containers:
        - name: spring-boot-kubernetes-skaffold-app
          image: spring-boot-kubernetes-skaffold
          ports:
            - containerPort: 6060