apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: spring-boot-kubernetes-skaffold
  name: spring-boot-kubernetes-skaffold
spec:
  ports:
    - port: 6060
      protocol: TCP
      targetPort: 6060
  selector:
    app: spring-boot-kubernetes-skaffold
  type: LoadBalancer
status:
  loadBalancer: {}